spring:
  application:
    name: bynature
  jpa:
    properties:
      jakarta.persistence.validation.mode: auto
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  mvc:
    throw-validation-exceptions: true
  datasource:
    url: jdbc:postgresql://localhost:5432/bynature
    username: postgres
    password: 231283
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: bynature


stripe:
  api:
    publicKey: pk_test_51QRIzAIeQeVliWL7EvK7n3Lr8iNmwIcYxkOjYHZ7UWJcpYWyFjRgeZEmgtHhtk2JV6ngn6BqUvKUojco8uKJ38Rr00KFkebO76
    secretKey: sk_test_51QRIzAIeQeVliWL7hs8NKCMtCZ6kPB97vISkKJHtlM3gfhmV6m5tkxbFgt2NPQH29068L5Bnp0R37Mj7aqOeHyfN007egZfviu
  webhook:
    secret: whsec_0f4635c0939d7e60dba42fe40913f6d5f8be935f5f1c1c28eeee505215e1913b

logging:
  level:
    root: INFO

application:
  security:
    oauth2:
      token:
        access-token-validity-seconds: 3600 # 1 hour
        refresh-token-validity-seconds: 86400 # 24 hours